sso_tom/chained/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views

from .views import (
    SingleObservationCreateView,
    ChainListView,
    ChainCreateView,
    ChainView,
    ChainedTargetDetailView,
    ChainTemplateCreateView,
    ChainTemplateListView,
    ChainTemplateView,
    ChainedTemplateCreateView,
)

app_name = "chains"

urlpatterns = [
    path("add/", ChainCreateView.as_view(), name="add_chain"),
    path(
        "templates/add/", ChainTemplateCreateView.as_view(), name="add_chain_template"
    ),
    path("", ChainListView.as_view(), name="chain_list"),
    path("templates/", ChainTemplateListView.as_view(), name="chain_template_list"),
    path("<int:chain_id>/", ChainView.as_view(), name="view_chain"),
    path(
        "templates/<int:template_id>/",
        ChainTemplateView.as_view(),
        name="view_chain_template",
    ),
    path(
        "<int:chain_id>/target/<int:pk>/",
        ChainedTargetDetailView.as_view(),
        name="chain_target",
    ),
    path(
        "<int:chain_id>/<str:facility>/create/",
        SingleObservationCreateView.as_view(),
        name="create",
    ),
    path(
        "templates/<int:template_id>/<str:facility>/create/",
        ChainedTemplateCreateView.as_view(),
        name="add_template",
    ),
]

sso_tom/sso_alerts/urls.py
from django.urls import path, include

from .views import (
    AlertListView,
    AlertStreamsCreateView,
    AlertStreamsUpdateView,
    toggle_active,
)

app_name = "sso_alerts"

urlpatterns = [
    path("", AlertListView.as_view(), name="alert_list"),
    path("create/", AlertStreamsCreateView.as_view(), name="alert_streams_create"),
    path(
        "update/<int:pk>/",
        AlertStreamsUpdateView.as_view(),
        name="alert_streams_update",
    ),
    path("toggle_active/<int:pk>/", toggle_active, name="toggle_active"),
]

sso_tom/sso_tom/urls.py
from django.urls import include, path

from .views import (
    AboutView,
    CustomObservationCreateView,
    CustomObservationTemplateCreateView,
    CustomObservationTemplateUpdateView,
    HowToView,
    page_not_found,
)

urlpatterns = [
    # disabled pages
    path("observations/status/", page_not_found, name="facility-status"),
    # required for custom validation of proposal id using user information
    path(
        "observations/<str:facility>/create/",
        CustomObservationCreateView.as_view(),
        name="create",
    ),
    path(
        "observations/template/<str:facility>/create/",
        CustomObservationTemplateCreateView.as_view(),
        name="template-create",
    ),
    path(
        "observations/template/<int:pk>/update/",
        CustomObservationTemplateUpdateView.as_view(),
        name="template-update",
    ),
    path(
        "observations/template/<int:pk>/",
        CustomObservationTemplateUpdateView.as_view(),
        name="template-detail",
    ),
    path(
        "",
        include(
            "tom_registration.registration_flows.open.urls", namespace="registration"
        ),
    ),
    path("", include("accounts.urls")),
    path("", include("tom_common.urls")),
    path("chains/", include("chained.urls")),
    path("sso_alerts/", include("sso_alerts.urls")),
    path("about/", AboutView.as_view(), name="about"),
    path("howto/", HowToView.as_view(), name="howto"),
]

sso_tom/templates/tom_common/base.html
{% load static bootstrap4 tom_common_extras %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'tom_common/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'tom_common/css/custom.css' %}">
    {% block additional_css %}
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static 'tom_common/img/favicon-32.ico' %}" sizes="32x32" />

    {% bootstrap_javascript jquery='True' %}

    <title>{% tom_name %} | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">{% tom_name %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% comment "Navbar Content Template" %}
          The navbar_content.html template defines the list (li) of nav-items that appear
          in the navbar-nav (ul).

          To customize your navbar-nav in your TOM:
          1. Create a templates/tom_common directory at the project level.
          2. Copy tom_common/templates/tom_common/navbar_content.html to your project's
             templates/tom_common directory.
          3. Customize your navbar content by editing your navbar_content.html.

          For more information,
          see the Django tutorial, "Writing your first Django app",
          Part 7, Section "Customize the admin look and feel"
          {% endcomment %}
          {% include 'tom_common/navbar_content.html' %}

        </ul>
        <ul class="navbar-nav ml-auto" id="login-buttons">
        {% navbar_login %}
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      {% bootstrap_messages %}
      <div class="content">
          {% block page_header %}
          {% endblock %}
        {% block content %}
        {% endblock %}
      </div>

    </main>

  {% block javascript %}
  {% endblock %}
  {% block extra_javascript %}
  {% endblock %}
  </body>
</html>

sso_tom/templates/tom_common/index.html
{% extends 'tom_common/base.html' %}
{% load static targets_extras observation_extras dataproduct_extras tom_common_extras %}
{% block title %}Home{% endblock %}
{% block content %}
<div>
  <h2 style="text-align: center;">Welcome to the Alert System for Siding Spring Observatory.</h2>
</div>
<br/>
<div class="row">
  <p class="text-center"><img src="https://www.sidingspringobservatory.com.au/img/SSO_pano_steve_cambell_2014.jpg" class="img-fluid mx-auto"></p>
</div>
<div class="col">
  <div class="card">
    <div class="card-header">
      Latest Targets
    </div>
    {% recent_targets %}
  </div>
</div>
{% endblock %}

sso_tom/templates/tom_common/navbar_content.html
{% load bootstrap4 %}
{% comment %}
The following nav-item list elements (li) are included in the tom_common/base.html navbar-nav (ul).
For customization instructions, see tom_common/base.html
{% endcomment %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% if request.resolver_match.namespace == 'targets' %}active{% endif %}" data-toggle="dropdown">Targets</a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'targets:list' %}">Targets</a>
        <a class="dropdown-item" href="{% url 'targets:targetgrouping' %}">Target Grouping</a>
    </div>
</li>
<li class="nav-item {% if request.resolver_match.namespace == 'alerts' %}active{% endif %}">
    <a class="nav-link" href="{% url 'alerts:list' %}">Alerts</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Observations</a>
    <ul class="dropdown-menu">
        <li class="nav-item {% if request.resolver_match.namespace == 'observations' %}active{% endif %}">
            <a class="nav-link" href="{% url 'tom_observations:list' %}" style="color:black">Observations</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'observations' %}active{% endif %}">
            <a class="nav-link" href="{% url 'tom_observations:group-list' %}" style="color:black">Observation
                Groups</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'observations' %}active{% endif %}">
            <a class="nav-link" href="{% url 'tom_observations:template-list' %}" style="color:black">Observation
                Templates</a>
        </li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Chains</a>
    <ul class="dropdown-menu">
        <li class="nav-item {% if request.resolver_match.namespace == 'chains' %}active{% endif %}">
            <a class="nav-link" href="{% url 'chains:chain_list' %}" style="color:black">Observation Chains</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'chains' %}active{% endif %}">
            <a class="nav-link" href="{% url 'chains:chain_template_list' %}" style="color:black">Chain Templates</a>
        </li>
    </ul>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'sso_alerts:alert_list' %}">Stream Alerts</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'howto' %}">User Guide</a>
</li>